import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, ArrowLeftRight, BarChart3, Boxes, ClipboardCheck, Database, History, Lock, LogOut, MinusCircle, PackagePlus, PlusCircle, RefreshCcw, Save, Settings, ShieldCheck, User, Users } from 'lucide-react'
import { supabase } from './supabaseClient'

const ADMIN_EMAILS = ['cfuentes@nohn-pa.org', 'crsfnts@gmail.com']
const getRoute = () => window.location.hash.replace('#/', '') || 'dashboard'
const keyFor = (itemId, locationId) => `${itemId}|${locationId}`
const monthStart = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-01` }
const safeError = (e) => e?.message || 'Unexpected error'
const itemLabel = (i) => i.manufacturer ? `${i.name} — ${i.manufacturer}` : i.name

function AuthScreen(){return <div className='loading'>Sign in required.</div>}
const SelectField=({label,value,onChange,children})=><label className='field'><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)} required>{children}</select></label>
const NumberField=({label,value,onChange})=><label className='field'><span>{label}</span><input type='number' value={value} onChange={e=>onChange(e.target.value)} required/></label>
const TextField=({label,value,onChange})=><label className='field'><span>{label}</span><input value={value} onChange={e=>onChange(e.target.value)} /></label>

export default function App(){
  const [session,setSession]=useState(null),[loading,setLoading]=useState(true),[active,setActive]=useState(getRoute())
  const [profile,setProfile]=useState(null),[items,setItems]=useState([]),[locations,setLocations]=useState([]),[pars,setPars]=useState([]),[transactions,setTransactions]=useState([]),[counts,setCounts]=useState([]),[profiles,setProfiles]=useState([]),[toast,setToast]=useState('')
  const isAdmin=profile?.role==='admin'&&profile?.active!==false
  useEffect(()=>{const sync=()=>setActive(getRoute());window.addEventListener('hashchange',sync);return()=>window.removeEventListener('hashchange',sync)},[])
  useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const {data:sub}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>sub.subscription.unsubscribe()},[])
  useEffect(()=>{if(session)loadAll()},[session])
  async function refreshProfile(){const {data}=await supabase.from('profiles').select('*').eq('id',session.user.id).maybeSingle();if(data)return data;const email=(session.user.email||'').toLowerCase();const role=ADMIN_EMAILS.includes(email)?'admin':'staff';await supabase.from('profiles').upsert({id:session.user.id,email:session.user.email,role,active:true},{onConflict:'id'});return (await supabase.from('profiles').select('*').eq('id',session.user.id).single()).data}
  async function loadAll(){setLoading(true);setProfile(await refreshProfile());const [i,l,p,t,c,pr]=await Promise.all([supabase.from('items').select('*').order('name'),supabase.from('locations').select('*').order('name'),supabase.from('par_levels').select('*'),supabase.from('transactions').select('*').order('created_at',{ascending:false}),supabase.from('monthly_counts').select('*').order('created_at',{ascending:false}),supabase.from('profiles').select('*').order('created_at')]);setItems(i.data||[]);setLocations(l.data||[]);setPars(p.data||[]);setTransactions(t.data||[]);setCounts(c.data||[]);setProfiles(pr.data||[]);setLoading(false)}
  const balances=useMemo(()=>transactions.reduce((a,tx)=>{const k=keyFor(tx.item_id,tx.location_id);a[k]=(a[k]||0)+Number(tx.quantity||0);return a},{}),[transactions]);
  const balanceFor=(i,l)=>balances[keyFor(i,l)]||0
  const usage=useMemo(()=>({item:new Set([...transactions.map(t=>t.item_id),...counts.map(c=>c.item_id),...pars.map(p=>p.item_id)]),location:new Set([...transactions.map(t=>t.location_id),...counts.map(c=>c.location_id),...pars.map(p=>p.location_id)])}),[transactions,counts,pars])
  async function insertTransaction(tx){const {error}=await supabase.from('transactions').insert({...tx,user_id:session.user.id});if(error)return setToast(safeError(error));await loadAll()}
  async function deleteItem(id){const {error}=await supabase.rpc('delete_item_if_unused',{item_id:id});if(error)setToast(safeError(error));else loadAll()}
  async function deleteLocation(id){const {error}=await supabase.rpc('delete_location_if_unused',{location_id:id});if(error)setToast(safeError(error));else loadAll()}
  if(loading&&!session)return <div className='loading'>Loading...</div>
  if(!session)return <AuthScreen/>
  const nav=[['dashboard','Dashboard'],['inventory','Inventory'],['admin','Admin'],['reports','Reports']]
  return <div className='appShell'><aside className='sidebar'><div className='logo'><Boxes/>Inventory Control</div><nav>{nav.filter(n=>isAdmin||n[0]!=='admin').map(([id,label])=><button key={id} className={active===id?'active':''} onClick={()=>window.location.hash=`/${id}`}>{label}</button>)}</nav><div className='sideFooter'><small>{isAdmin?'Admin view':'Staff view'}</small><button onClick={()=>supabase.auth.signOut()}><LogOut size={14}/> Sign out</button></div></aside><main className='main'><header className='topbar'><h1>{nav.find(n=>n[0]===active)?.[1]||'Dashboard'}</h1><button className='ghostButton' onClick={loadAll}><RefreshCcw size={14}/>Refresh</button></header>{toast&&<div className='toast'>{toast}</div>}
    {active==='dashboard'&&<Dashboard items={items} locations={locations} pars={pars} transactions={transactions} counts={counts} balances={balances}/>}
    {active==='inventory'&&<InventoryActions items={items.filter(i=>i.active!==false)} locations={locations.filter(l=>l.active!==false)} insertTransaction={insertTransaction} balanceFor={balanceFor} session={session} loadAll={loadAll} setToast={setToast}/>}    
    {active==='admin' && (isAdmin?<Setup {...{profiles,items,locations,pars,counts,transactions,usage,setToast,loadAll,insertTransaction,balanceFor,deleteItem,deleteLocation}}/>:<section className='panel'><Lock/>Admin required.</section>)}
    {active==='reports'&&<HistoryView transactions={transactions} items={items} locations={locations}/>}
  </main></div>
}

function Dashboard({items,locations,pars,transactions,balances}){const activeItems=items.filter(i=>i.active!==false);const activeLocations=locations.filter(l=>l.active!==false);const parMap=new Map(pars.map(p=>[`${p.item_id}|${p.location_id}`,p]));const rows=[...parMap.entries()].map(([k,p])=>({k,...p,current:balances[k]||0,item:items.find(i=>i.id===p.item_id),loc:locations.find(l=>l.id===p.location_id)}));const below=rows.filter(r=>r.current<Number(r.par_level||0));const near=rows.filter(r=>r.current>=Number(r.par_level||0)&&r.current<Number(r.target_level||r.par_level||0));return <div className='gridStack'><section className='kpiGrid'>{[['Total Active Items',activeItems.length],['Total Locations',activeLocations.length],['Items Below Par',below.length],['Items Near Par',near.length],['Total Units',Object.values(balances).reduce((a,b)=>a+b,0)],['Recent Corrections',transactions.filter(t=>t.action==='ADMIN_ADJUSTMENT').length],['Monthly Adjustments',transactions.filter(t=>t.action==='MONTHLY_ADJUSTMENT').length]].map(([l,v])=><div key={l} className='kpi'><h4>{l}</h4><strong>{v}</strong></div>)}</section><section className='panel'><h2>Below Par Watchlist</h2><div className='tableWrap'><table><thead><tr><th>Item</th><th>Manufacturer</th><th>Location</th><th>Current</th><th>Par</th><th>Target</th></tr></thead><tbody>{below.slice(0,10).map(r=><tr key={r.k}><td>{r.item?.name}</td><td>{r.item?.manufacturer||'—'}</td><td>{r.loc?.name}</td><td>{r.current}</td><td>{r.par_level}</td><td>{r.target_level}</td></tr>)}</tbody></table></div>{!below.length&&<p>No items below par.</p>}</section></div>}

function InventoryActions(props){return <div className='gridStack'><section className='panel'><h2>Inventory Actions</h2></section><TransactionFormBase mode='ADD' {...props}/><TransactionFormBase mode='REMOVE' {...props}/><TransferStock {...props}/><MonthlyCount {...props}/></div>}
function Setup({ profiles, items, locations, pars, usage, setToast, loadAll, insertTransaction, balanceFor, deleteItem, deleteLocation }){const [itemName,setItemName]=useState(''),[manufacturer,setManufacturer]=useState(''),[category,setCategory]=useState('Medication'),[locationName,setLocationName]=useState(''); async function addItem(e){e.preventDefault();const {error}=await supabase.from('items').insert({name:itemName,category,manufacturer});if(error)setToast(error.message);else{setItemName('');setManufacturer('');loadAll()}} async function addLocation(e){e.preventDefault();const {error}=await supabase.from('locations').insert({name:locationName});if(error)setToast(error.message);else{setLocationName('');loadAll()}} async function toggle(table,row){await supabase.from(table).update({active:!row.active}).eq('id',row.id);loadAll()} async function updateUser(id,patch){await supabase.from('profiles').update(patch).eq('id',id);loadAll()} async function deletePar(id){if(confirm('Delete par level record?')){await supabase.from('par_levels').delete().eq('id',id);loadAll()}}
return <div className='gridStack'><section className='panel'><h2>User Management</h2>{profiles.map(p=><div key={p.id}>{p.email} <button onClick={()=>updateUser(p.id,{active:!p.active})}>{p.active?'Deactivate User':'Reactivate User'}</button></div>)}</section><section className='twoCol'><form className='panel formStack' onSubmit={addItem}><h2>Items</h2><TextField label='Name' value={itemName} onChange={setItemName}/><TextField label='Manufacturer' value={manufacturer} onChange={setManufacturer}/><TextField label='Category' value={category} onChange={setCategory}/><button className='primaryButton'><PackagePlus size={16}/>Add Item</button>{items.map(i=><div key={i.id}>{itemLabel(i)} <button type='button' onClick={()=>toggle('items',i)}>{i.active?'Archive':'Unarchive'}</button> <button type='button' onClick={()=>usage.item.has(i.id)?setToast('This item has inventory history and cannot be permanently deleted. Archive it instead to preserve the audit trail.'):confirm('Are you sure you want to permanently delete this item? This cannot be undone.')&&deleteItem(i.id)}>Delete</button></div>)}</form><form className='panel formStack' onSubmit={addLocation}><h2>Locations</h2><TextField label='Name' value={locationName} onChange={setLocationName}/><button className='primaryButton'><Database size={16}/>Add Location</button>{locations.map(l=><div key={l.id}>{l.name} <button type='button' onClick={()=>toggle('locations',l)}>{l.active?'Archive':'Unarchive'}</button> <button type='button' onClick={()=>usage.location.has(l.id)?setToast('This location has inventory history and cannot be permanently deleted. Archive it instead to preserve the audit trail.'):confirm('Are you sure you want to permanently delete this location? This cannot be undone.')&&deleteLocation(l.id)}>Delete</button></div>)}</form></section><section className='panel'><h2>Par Levels</h2>{pars.map(p=><div key={p.id}>{p.item_id} / {p.location_id} <button onClick={()=>deletePar(p.id)}>Delete</button></div>)}</section></div>}

function TransactionFormBase({ mode, items, locations, insertTransaction, balanceFor }) { const [itemId, setItemId] = useState(''); const [locationId, setLocationId] = useState(''); const [quantity, setQuantity] = useState(''); const q = Number(quantity || 0); const current = itemId && locationId ? balanceFor(itemId, locationId) : 0; const signedQty = mode === 'REMOVE' ? -Math.abs(q) : Math.abs(q); const invalidRemove = mode === 'REMOVE' && q > current; async function save(e) { e.preventDefault(); if (invalidRemove) return; await insertTransaction({ item_id: itemId, location_id: locationId, action: mode, quantity: signedQty, reason: mode==='ADD'?'Received stock':'Inventory removal' }) } return <section className="panel"><h3>{mode==='ADD'?'Add Stock':'Remove Stock'}</h3><form onSubmit={save} className="formGrid"><SelectField label="Item" value={itemId} onChange={setItemId}><option value="">Choose item...</option>{items.map((i) => <option key={i.id} value={i.id}>{itemLabel(i)}</option>)}</SelectField><SelectField label="Location" value={locationId} onChange={setLocationId}><option value="">Choose location...</option>{locations.map((l) => <option key={l.id} value={l.id}>{l.name}</option>)}</SelectField><NumberField label="Quantity" value={quantity} onChange={setQuantity} />{invalidRemove && <div className="warning full"><AlertTriangle size={18} /> Cannot remove more than current balance.</div>}<button className="primaryButton full">Save</button></form></section> }
function TransferStock({ items, locations, session, loadAll, setToast, balanceFor }) { const [itemId, setItemId] = useState(''); const [fromId, setFromId] = useState(''); const [toId, setToId] = useState(''); const [quantity, setQuantity] = useState(''); const q = Number(quantity || 0); const current = itemId && fromId ? balanceFor(itemId, fromId) : 0; const invalid = !itemId || !fromId || !toId || fromId === toId || !q || q > current; async function save(e) { e.preventDefault(); if (invalid) return; const { error } = await supabase.from('transactions').insert([{ user_id: session.user.id, item_id: itemId, location_id: fromId, action: 'TRANSFER_OUT', quantity: -Math.abs(q), reason: 'Transfer out' }, { user_id: session.user.id, item_id: itemId, location_id: toId, action: 'TRANSFER_IN', quantity: Math.abs(q), reason: 'Transfer in' }]); if (error) setToast(safeError(error)); else await loadAll() } return <section className="panel"><h3>Transfer</h3><form onSubmit={save} className="formGrid"><SelectField label="Item" value={itemId} onChange={setItemId}><option value="">Choose item...</option>{items.map(i => <option key={i.id} value={i.id}>{itemLabel(i)}</option>)}</SelectField><SelectField label="From" value={fromId} onChange={setFromId}><option value="">Choose source...</option>{locations.map(l => <option key={l.id} value={l.id}>{l.name}</option>)}</SelectField><SelectField label="To" value={toId} onChange={setToId}><option value="">Choose destination...</option>{locations.map(l => <option key={l.id} value={l.id}>{l.name}</option>)}</SelectField><NumberField label="Quantity" value={quantity} onChange={setQuantity} /><button className="primaryButton full">Save Transfer</button></form></section> }
function MonthlyCount({ items, locations, session, loadAll, setToast, balanceFor }) { const [itemId, setItemId] = useState(''); const [locationId, setLocationId] = useState(''); const [physical, setPhysical] = useState(''); const [countMonth, setCountMonth] = useState(monthStart()); const systemBalance = itemId && locationId ? balanceFor(itemId, locationId) : 0; const difference = Number(physical || 0) - Number(systemBalance); async function save(e) { e.preventDefault(); const { data, error } = await supabase.from('monthly_counts').insert({ user_id: session.user.id, count_month: countMonth, item_id: itemId, location_id: locationId, system_balance: systemBalance, physical_count: Number(physical), difference }).select().single(); if (error) return setToast(safeError(error)); if (difference !== 0) await supabase.from('transactions').insert({ user_id: session.user.id, item_id: itemId, location_id: locationId, action: 'MONTHLY_ADJUSTMENT', quantity: difference, reason: 'Monthly physical count adjustment', monthly_count_id: data.id }); await loadAll() } return <section className="panel"><h3>Monthly Count</h3><form onSubmit={save} className="formGrid"><label className="field"><span>Count Month</span><input type="date" value={countMonth} onChange={(e) => setCountMonth(e.target.value)} /></label><SelectField label="Item" value={itemId} onChange={setItemId}><option value="">Choose item...</option>{items.map(i => <option key={i.id} value={i.id}>{itemLabel(i)}</option>)}</SelectField><SelectField label="Location" value={locationId} onChange={setLocationId}><option value="">Choose location...</option>{locations.map(l => <option key={l.id} value={l.id}>{l.name}</option>)}</SelectField><NumberField label="Physical" value={physical} onChange={setPhysical} /><button className="primaryButton full">Save Count</button></form></section> }
function HistoryView({ transactions, items, locations }) {const item=(id)=>items.find(x=>x.id===id); const loc=(id)=>locations.find(x=>x.id===id); return <section className="panel"><h2>History / Export</h2><div className="tableWrap"><table><thead><tr><th>Date</th><th>Action</th><th>Item</th><th>Location</th><th>Qty</th></tr></thead><tbody>{transactions.map((t) => <tr key={t.id}><td>{new Date(t.created_at).toLocaleString()}</td><td>{t.action}</td><td>{itemLabel(item(t.item_id)||{name:'Unknown'})}</td><td>{loc(t.location_id)?.name||'Unknown'}</td><td>{t.quantity}</td></tr>)}</tbody></table></div></section> }
