import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, ArrowLeftRight, BarChart3, Boxes, ClipboardCheck, Database, History, Lock, LogOut, MinusCircle, PackagePlus, PlusCircle, RefreshCcw, Save, Settings, ShieldCheck, User, Users } from 'lucide-react'
import { supabase } from './supabaseClient'

const ADMIN_EMAILS = ['cfuentes@nohn-pa.org', 'crsfnts@gmail.com']
const ACTIONS = { OPENING_BALANCE: 'Opening Balance', ADD: 'Add Stock', REMOVE: 'Remove Stock', TRANSFER_IN: 'Transfer In', TRANSFER_OUT: 'Transfer Out', ADMIN_ADJUSTMENT: 'Admin Adjustment', MONTHLY_ADJUSTMENT: 'Monthly Adjustment' }
const getRoute = () => window.location.hash.replace('#/', '') || 'dashboard'
const moneylessNumber = (v) => Number.isInteger(Number(v || 0)) ? Number(v || 0).toString() : Number(v || 0).toFixed(2)
const keyFor = (itemId, locationId) => `${itemId}|${locationId}`
const monthStart = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-01` }
const isPermissionError = (e) => e?.code === '42501' || /permission|policy|row-level/i.test(e?.message || '')
const safeError = (e) => isPermissionError(e) ? 'You do not have permission to perform this action.' : e?.message

function AuthScreen() { const [mode, setMode] = useState('signin'); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(false); async function submit(e) { e.preventDefault(); setLoading(true); setMessage(''); const result = mode === 'signin' ? await supabase.auth.signInWithPassword({ email, password }) : await supabase.auth.signUp({ email, password }); setLoading(false); if (result.error) setMessage(result.error.message); else if (mode === 'signup') setMessage('Account created. If email confirmation is enabled, check your email before signing in.') } return <div className="authShell"><div className="authCard"><div className="brandMark"><ShieldCheck size={32} /></div><h1>Inventory Control</h1><form onSubmit={submit} className="authForm"><label>Email</label><input value={email} onChange={(e) => setEmail(e.target.value)} type="email" required /><label>Password</label><input value={password} onChange={(e) => setPassword(e.target.value)} type="password" minLength={6} required /><button className="primaryButton" disabled={loading}>{loading ? 'Working...' : mode === 'signin' ? 'Sign In' : 'Create Account'}</button></form>{message && <div className="notice">{message}</div>}<button className="linkButton" onClick={() => setMode(mode === 'signin' ? 'signup' : 'signin')}>{mode === 'signin' ? 'Need an account? Create one' : 'Already have an account? Sign in'}</button></div></div> }

const SelectField = ({ label, value, onChange, children }) => <label className="field"><span>{label}</span><select value={value} onChange={(e) => onChange(e.target.value)} required>{children}</select></label>
const NumberField = ({ label, value, onChange, min = 0 }) => <label className="field"><span>{label}</span><input value={value} min={min} onChange={(e) => onChange(e.target.value)} type="number" step="0.01" required /></label>
const TextField = ({ label, value, onChange }) => <label className="field"><span>{label}</span><input value={value} onChange={(e) => onChange(e.target.value)} /></label>

export default function App() {
  const [session, setSession] = useState(null); const [loading, setLoading] = useState(true); const [active, setActive] = useState(getRoute());
  const [profile, setProfile] = useState(null); const [items, setItems] = useState([]); const [locations, setLocations] = useState([]); const [pars, setPars] = useState([]); const [transactions, setTransactions] = useState([]); const [counts, setCounts] = useState([]); const [profiles, setProfiles] = useState([]); const [toast, setToast] = useState('')
  const isAdmin = profile?.role === 'admin' && profile?.active !== false; const isStaff = !isAdmin

  useEffect(() => { const sync = () => setActive(getRoute()); window.addEventListener('hashchange', sync); return () => window.removeEventListener('hashchange', sync) }, [])
  useEffect(() => { supabase.auth.getSession().then(({ data }) => { setSession(data.session); setLoading(false) }); const { data: sub } = supabase.auth.onAuthStateChange((_e, s) => setSession(s)); return () => sub.subscription.unsubscribe() }, [])
  useEffect(() => { if (session) loadAll() }, [session])

  async function refreshProfile() {
    const { data, error } = await supabase.from('profiles').select('*').eq('id', session.user.id).maybeSingle()
    if (!data && !error) {
      const email = (session.user.email || '').toLowerCase(); const role = ADMIN_EMAILS.includes(email) ? 'admin' : 'staff'
      await supabase.from('profiles').upsert({ id: session.user.id, email: session.user.email, role, active: true }, { onConflict: 'id' })
      return (await supabase.from('profiles').select('*').eq('id', session.user.id).maybeSingle()).data
    }
    return data
  }

  async function loadAll() {
    setLoading(true); const me = await refreshProfile(); setProfile(me)
    const [i, l, pl, t, c, pr] = await Promise.all([
      supabase.from('items').select('*').order('name'), supabase.from('locations').select('*').order('name'), supabase.from('par_levels').select('*'), supabase.from('transactions').select('*').order('created_at', { ascending: false }), supabase.from('monthly_counts').select('*').order('created_at', { ascending: false }), supabase.from('profiles').select('*').order('created_at')
    ])
    const err = [i.error, l.error, pl.error, t.error, c.error, pr.error].find(Boolean); if (err) setToast(safeError(err))
    setItems(i.data || []); setLocations(l.data || []); setPars(pl.data || []); setTransactions(t.data || []); setCounts(c.data || []); setProfiles(pr.data || []); setLoading(false)
  }

  const balances = useMemo(() => transactions.reduce((a, tx) => { const k = keyFor(tx.item_id, tx.location_id); a[k] = (a[k] || 0) + Number(tx.quantity || 0); return a }, {}), [transactions])
  const balanceFor = (itemId, locationId) => balances[keyFor(itemId, locationId)] || 0
  const itemName = (id) => items.find((x) => x.id === id)?.name || 'Unknown item'; const locationName = (id) => locations.find((x) => x.id === id)?.name || 'Unknown location'

  async function insertTransaction(tx) { const { error } = await supabase.from('transactions').insert({ ...tx, user_id: session.user.id }); if (error) return setToast(safeError(error)), false; await loadAll(); return true }
  if (loading && !session) return <div className="loading">Loading...</div>
  if (!session) return <AuthScreen />

  const nav = [['dashboard', 'Dashboard', <BarChart3 size={18} />], ['add', 'Add Stock', <PlusCircle size={18} />], ['remove', 'Remove Stock', <MinusCircle size={18} />], ['transfer', 'Transfer', <ArrowLeftRight size={18} />], ['monthly', 'Monthly Count', <ClipboardCheck size={18} />], ['setup', 'Setup / Par', <Settings size={18} />], ['history', 'History', <History size={18} />]]
  return <div className="appShell"><aside className="sidebar"><div className="logo"><div><Boxes size={26} /></div><span>Inventory<br />Control</span></div><nav>{nav.filter(([id]) => isAdmin || id !== 'setup').map(([id, label, icon]) => <button key={id} className={active === id ? 'active' : ''} onClick={() => window.location.hash = `/${id}`}>{icon}{label}</button>)}</nav><div className="sideFooter"><User size={16} /> <span>{session.user.email}</span><small>{isAdmin ? 'Admin view' : 'Staff view'}</small><button onClick={() => supabase.auth.signOut()}><LogOut size={16} /> Sign out</button></div></aside><main className="main"><header className="topbar"><h1>{nav.find(([id]) => id === active)?.[1] || 'Dashboard'}</h1><button className="ghostButton" onClick={loadAll}><RefreshCcw size={16} /> Refresh</button></header>{toast && <div className="toast"><span>{toast}</span><button onClick={() => setToast('')}>×</button></div>}
    {active === 'setup' && !isAdmin ? <section className="panel"><div className="warning"><Lock size={18} /> Admin access required.</div></section> : null}
    {active === 'dashboard' && <div className="panel">Transactions: {transactions.length}</div>}
    {active === 'add' && <TransactionFormBase mode="ADD" items={items.filter(i => i.active !== false)} locations={locations.filter(l => l.active !== false)} insertTransaction={insertTransaction} balanceFor={balanceFor} />}
    {active === 'remove' && <TransactionFormBase mode="REMOVE" items={items.filter(i => i.active !== false)} locations={locations.filter(l => l.active !== false)} insertTransaction={insertTransaction} balanceFor={balanceFor} />}
    {active === 'transfer' && <TransferStock items={items.filter(i => i.active !== false)} locations={locations.filter(l => l.active !== false)} session={session} loadAll={loadAll} setToast={setToast} balanceFor={balanceFor} />}
    {active === 'monthly' && <MonthlyCount items={items.filter(i => i.active !== false)} locations={locations.filter(l => l.active !== false)} session={session} loadAll={loadAll} setToast={setToast} balanceFor={balanceFor} />}
    {active === 'setup' && isAdmin && <Setup profiles={profiles} items={items} locations={locations} pars={pars} setToast={setToast} loadAll={loadAll} insertTransaction={insertTransaction} balanceFor={balanceFor} transactions={transactions} />}
    {active === 'history' && <HistoryView transactions={transactions} itemName={itemName} locationName={locationName} />}
  </main></div>
}

function Setup({ profiles, items, locations, pars, setToast, loadAll, insertTransaction, balanceFor, transactions }) { /* compact admin tools */
  const [itemName, setItemName] = useState(''); const [category, setCategory] = useState('Medication'); const [locationName, setLocationName] = useState(''); const [parItem, setParItem] = useState(''); const [parLocation, setParLocation] = useState(''); const [par, setPar] = useState(''); const [target, setTarget] = useState(''); const [adjItem, setAdjItem] = useState(''); const [adjLocation, setAdjLocation] = useState(''); const [desiredBalance, setDesiredBalance] = useState(''); const [adjReason, setAdjReason] = useState('')
  async function addItem(e) { e.preventDefault(); const { error } = await supabase.from('items').insert({ name: itemName, category }); if (error) setToast(safeError(error)); else { setItemName(''); await loadAll() } }
  async function addLocation(e) { e.preventDefault(); const { error } = await supabase.from('locations').insert({ name: locationName }); if (error) setToast(safeError(error)); else { setLocationName(''); await loadAll() } }
  async function savePar(e) { e.preventDefault(); const { error } = await supabase.from('par_levels').upsert({ item_id: parItem, location_id: parLocation, par_level: Number(par), target_level: Number(target) }, { onConflict: 'item_id,location_id' }); if (error) setToast(safeError(error)); else await loadAll() }
  async function toggle(table, row) { const { error } = await supabase.from(table).update({ active: !row.active }).eq('id', row.id); if (error) setToast(safeError(error)); else await loadAll() }
  async function updateUser(id, patch) { const { error } = await supabase.from('profiles').update(patch).eq('id', id); if (error) setToast(safeError(error)); else await loadAll() }
  async function saveAdjustment(e) { e.preventDefault(); const current = balanceFor(adjItem, adjLocation); const desired = Number(desiredBalance); const delta = desired - current; if (!adjReason.trim()) return setToast('Reason is required for admin adjustments.'); const hasOpen = transactions.some(t => t.item_id === adjItem && t.location_id === adjLocation && t.action === 'OPENING_BALANCE'); const action = hasOpen ? 'ADMIN_ADJUSTMENT' : 'OPENING_BALANCE'; const ok = await insertTransaction({ item_id: adjItem, location_id: adjLocation, action, quantity: delta, reason: adjReason, notes: `Desired balance ${desired}` }); if (ok) { setDesiredBalance(''); setAdjReason('') } }
  return <div className="gridStack"><section className="panel"><h2><Users size={16} /> User Management</h2><div className="tableWrap"><table><thead><tr><th>Email</th><th>Role</th><th>Active</th><th>Created</th><th>Actions</th></tr></thead><tbody>{profiles.map((p) => <tr key={p.id}><td>{p.email}</td><td>{p.role}</td><td>{String(p.active)}</td><td>{new Date(p.created_at).toLocaleDateString()}</td><td><button onClick={() => updateUser(p.id, { role: p.role === 'admin' ? 'staff' : 'admin' })}>Toggle role</button><button onClick={() => updateUser(p.id, { active: !p.active })}>{p.active ? 'Deactivate' : 'Reactivate'}</button></td></tr>)}</tbody></table></div></section><section className="twoCol"><form className="panel formStack" onSubmit={addItem}><h2>Item Management</h2><TextField label="Item Name" value={itemName} onChange={setItemName} /><TextField label="Category" value={category} onChange={setCategory} /><button className="primaryButton"><PackagePlus size={16} /> Add Item</button>{items.map(i => <button type="button" key={i.id} onClick={() => toggle('items', i)}>{i.name}: {i.active ? 'Deactivate' : 'Activate'}</button>)}</form><form className="panel formStack" onSubmit={addLocation}><h2>Location Management</h2><TextField label="Location Name" value={locationName} onChange={setLocationName} /><button className="primaryButton"><Database size={16} /> Add Location</button>{locations.map(l => <button type="button" key={l.id} onClick={() => toggle('locations', l)}>{l.name}: {l.active ? 'Deactivate' : 'Activate'}</button>)}</form></section><form className="panel formGrid" onSubmit={savePar}><h2 className="full">Par Level Management</h2><SelectField label="Item" value={parItem} onChange={setParItem}><option value="">Choose item...</option>{items.map(i => <option key={i.id} value={i.id}>{i.name}</option>)}</SelectField><SelectField label="Location" value={parLocation} onChange={setParLocation}><option value="">Choose location...</option>{locations.map(l => <option key={l.id} value={l.id}>{l.name}</option>)}</SelectField><NumberField label="Par" value={par} onChange={setPar} /><NumberField label="Target" value={target} onChange={setTarget} /><button className="primaryButton full"><Save size={16} /> Save Par</button></form><form className="panel formGrid" onSubmit={saveAdjustment}><h2 className="full">Opening Inventory / Admin Adjustment</h2><SelectField label="Item" value={adjItem} onChange={setAdjItem}><option value="">Choose item...</option>{items.map(i => <option key={i.id} value={i.id}>{i.name}</option>)}</SelectField><SelectField label="Location" value={adjLocation} onChange={setAdjLocation}><option value="">Choose location...</option>{locations.map(l => <option key={l.id} value={l.id}>{l.name}</option>)}</SelectField><NumberField label="Desired balance" value={desiredBalance} onChange={setDesiredBalance} /><TextField label="Reason" value={adjReason} onChange={setAdjReason} /><button className="primaryButton full">Save</button></form></div>
}

function TransactionFormBase({ mode, items, locations, insertTransaction, balanceFor }) { const [itemId, setItemId] = useState(''); const [locationId, setLocationId] = useState(''); const [quantity, setQuantity] = useState(''); const [reason, setReason] = useState(mode === 'ADD' ? 'Received stock' : 'Inventory removal'); const q = Number(quantity || 0); const current = itemId && locationId ? balanceFor(itemId, locationId) : 0; const signedQty = mode === 'REMOVE' ? -Math.abs(q) : Math.abs(q); const invalidRemove = mode === 'REMOVE' && q > current; async function save(e) { e.preventDefault(); if (invalidRemove) return; await insertTransaction({ item_id: itemId, location_id: locationId, action: mode, quantity: signedQty, reason }) } return <section className="panel"><form onSubmit={save} className="formGrid"><SelectField label="Item" value={itemId} onChange={setItemId}><option value="">Choose item...</option>{items.map((i) => <option key={i.id} value={i.id}>{i.name}</option>)}</SelectField><SelectField label="Location" value={locationId} onChange={setLocationId}><option value="">Choose location...</option>{locations.map((l) => <option key={l.id} value={l.id}>{l.name}</option>)}</SelectField><NumberField label="Quantity" value={quantity} onChange={setQuantity} />{invalidRemove && <div className="warning full"><AlertTriangle size={18} /> Cannot remove more than current balance.</div>}<button className="primaryButton full">Save</button></form></section> }
function TransferStock({ items, locations, session, loadAll, setToast, balanceFor }) { const [itemId, setItemId] = useState(''); const [fromId, setFromId] = useState(''); const [toId, setToId] = useState(''); const [quantity, setQuantity] = useState(''); const q = Number(quantity || 0); const current = itemId && fromId ? balanceFor(itemId, fromId) : 0; const invalid = !itemId || !fromId || !toId || fromId === toId || !q || q > current; async function save(e) { e.preventDefault(); if (invalid) return; const { error } = await supabase.from('transactions').insert([{ user_id: session.user.id, item_id: itemId, location_id: fromId, action: 'TRANSFER_OUT', quantity: -Math.abs(q), reason: 'Transfer out' }, { user_id: session.user.id, item_id: itemId, location_id: toId, action: 'TRANSFER_IN', quantity: Math.abs(q), reason: 'Transfer in' }]); if (error) setToast(safeError(error)); else await loadAll() } return <section className="panel"><form onSubmit={save} className="formGrid"><SelectField label="Item" value={itemId} onChange={setItemId}><option value="">Choose item...</option>{items.map(i => <option key={i.id} value={i.id}>{i.name}</option>)}</SelectField><SelectField label="From" value={fromId} onChange={setFromId}><option value="">Choose source...</option>{locations.map(l => <option key={l.id} value={l.id}>{l.name}</option>)}</SelectField><SelectField label="To" value={toId} onChange={setToId}><option value="">Choose destination...</option>{locations.map(l => <option key={l.id} value={l.id}>{l.name}</option>)}</SelectField><NumberField label="Quantity" value={quantity} onChange={setQuantity} /><button className="primaryButton full">Save Transfer</button></form></section> }
function MonthlyCount({ items, locations, session, loadAll, setToast, balanceFor }) { const [itemId, setItemId] = useState(''); const [locationId, setLocationId] = useState(''); const [physical, setPhysical] = useState(''); const [countMonth, setCountMonth] = useState(monthStart()); const systemBalance = itemId && locationId ? balanceFor(itemId, locationId) : 0; const difference = Number(physical || 0) - Number(systemBalance); async function save(e) { e.preventDefault(); const { data, error } = await supabase.from('monthly_counts').insert({ user_id: session.user.id, count_month: countMonth, item_id: itemId, location_id: locationId, system_balance: systemBalance, physical_count: Number(physical), difference }).select().single(); if (error) return setToast(safeError(error)); if (difference !== 0) await supabase.from('transactions').insert({ user_id: session.user.id, item_id: itemId, location_id: locationId, action: 'MONTHLY_ADJUSTMENT', quantity: difference, reason: 'Monthly physical count adjustment', monthly_count_id: data.id }); await loadAll() } return <section className="panel"><form onSubmit={save} className="formGrid"><label className="field"><span>Count Month</span><input type="date" value={countMonth} onChange={(e) => setCountMonth(e.target.value)} /></label><SelectField label="Item" value={itemId} onChange={setItemId}><option value="">Choose item...</option>{items.map(i => <option key={i.id} value={i.id}>{i.name}</option>)}</SelectField><SelectField label="Location" value={locationId} onChange={setLocationId}><option value="">Choose location...</option>{locations.map(l => <option key={l.id} value={l.id}>{l.name}</option>)}</SelectField><NumberField label="Physical" value={physical} onChange={setPhysical} /><button className="primaryButton full">Save Count</button></form></section> }
function HistoryView({ transactions, itemName, locationName }) { return <section className="panel"><h2>History</h2><div className="tableWrap"><table><thead><tr><th>Date</th><th>Action</th><th>Item</th><th>Location</th><th>Qty</th></tr></thead><tbody>{transactions.map((t) => <tr key={t.id}><td>{new Date(t.created_at).toLocaleString()}</td><td>{ACTIONS[t.action] || t.action}</td><td>{itemName(t.item_id)}</td><td>{locationName(t.location_id)}</td><td>{moneylessNumber(t.quantity)}</td></tr>)}</tbody></table></div></section> }
